### PR TITLE
(optimize): Update the total chaos count logic

### LINKED ISSUE #92: (enhancement): Optimize the total chaos count for enabled application
## BUG REPORT

**What happened**:

Optimize the total enabled chaos count for the enabled application.
Reference comment: https://github.com/litmuschaos/chaos-operator/pull/90#discussion_r347314856

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by chandankumar4**
Signed-off-by: chandan kumar <chandan.kr404@gmail.com>

**What this PR does / why we need it**:

- Optimize the total chaos count logic
    - **Explanation**: If the `5` application have the same label then for loop will run only once and if he got the chaos count greater than `1` then the loop will break with the error `too many chaos counts`
  
- Refactor the function `CheckDeploymentAnnotation`, `CheckDaemonSetAnnotation` and `CheckStatefulSetAnnotation` according to BCH rule

**Which issue this PR fixes**: #92 

**Checklist:**
- [x] Fixes #92 
- [ ] Labelled this PR & related issue with `documentation` tag
- [ ] PR messages has document related information
- [x] Labelled this PR & related issue with `breaking-changes` tag
- [ ] PR messages has breaking changes related information
- [ ] Labelled this PR & related issue with `requires-upgrade` tag
- [ ] PR messages has upgrade related information
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

File: pkg/controller/resource/daemonset.go [hunk 1]
```diff
@@ -56,13 +58,16 @@ func getDaemonSetLists(clientSet *kubernetes.Clientset, ce *chaosTypes.EngineInf
...
-func checkForEnabledChaos(targetAppList *v1.DaemonSetList, ce *chaosTypes.EngineInfo) (*chaosTypes.EngineInfo, int) {
+func checkForChaosEnabledDaemonSet(targetAppList *v1.DaemonSetList, ce *chaosTypes.EngineInfo) (*chaosTypes.EngineInfo, int, error) {
 	chaosEnabledDaemonSet := 0
 	for _, daemonSet := range targetAppList.Items {
 		ce.AppName = daemonSet.ObjectMeta.Name
 		ce.AppUUID = daemonSet.ObjectMeta.UID
 		annotationValue := daemonSet.ObjectMeta.GetAnnotations()[ChaosAnnotationKey]
 		chaosEnabledDaemonSet = CountTotalChaosEnabled(annotationValue, chaosEnabledDaemonSet)
+		if chaosEnabledDaemonSet > 1 {
+			return ce, chaosEnabledDaemonSet, errors.New("too many chaos candidates with same label, either provide unique labels or annotate only desired app for chaos")
```
Comment (ksatchit) [inline pkg/controller/resource/daemonset.go]: Changes are good @chandankumar4 . Considering we now have separate files for each resource type - can we customize the error messages accordingly too? This might give better user experience. 

Ex: "too many deployments with specified label are annotated for chaos, either provide unique labels or annotate only desired app for chaos"

Comment (chandankumar4) [reply pkg/controller/resource/daemonset.go]: Done
